#! bash oh-my-bash.module

source "$OSH/themes/powerline-naked/powerline-naked.base.sh"

PROMPT_CHAR=${POWERLINE_PROMPT_CHAR:=""}
POWERLINE_LEFT_SEPARATOR=${POWERLINE_LEFT_SEPARATOR:=""}

USER_INFO_SSH_CHAR=${POWERLINE_USER_INFO_SSH_CHAR:=" "}
USER_INFO_THEME_PROMPT_COLOR=${POWERLINE_USER_INFO_THEME_PROMPT_COLOR:=240}
USER_INFO_THEME_PROMPT_SECONDARY_COLOR="${POWERLINE_USER_INFO_THEME_PROMPT_SECONDARY_COLOR:=-}"
USER_INFO_THEME_PROMPT_COLOR_SUDO=${POWERLINE_USER_INFO_THEME_PROMPT_COLOR_SUDO:=202}

PYTHON_VENV_CHAR=${POWERLINE_PYTHON_VENV_CHAR:="❲p❳ "}
CONDA_PYTHON_VENV_CHAR=${POWERLINE_CONDA_PYTHON_VENV_CHAR:="❲c❳ "}
PYTHON_VENV_THEME_PROMPT_COLOR=${POWERLINE_PYTHON_VENV_THEME_PROMPT_COLOR:=35}

SCM_NONE_CHAR="${POWERLINE_SCM_NONE_CHAR:=}"
SCM_GIT_CHAR=${POWERLINE_SCM_GIT_CHAR:=" "}
SCM_THEME_PROMPT_CLEAN="${POWERLINE_SCM_THEME_PROMPT_CLEAN:=}"
SCM_THEME_PROMPT_DIRTY="${POWERLINE_SCM_THEME_PROMPT_DIRTY:=}"
SCM_THEME_PROMPT_COLOR=${POWERLINE_SCM_THEME_PROMPT_COLOR:=238}
SCM_THEME_PROMPT_CLEAN_COLOR=${POWERLINE_SCM_THEME_PROMPT_CLEAN_COLOR:=25}
SCM_THEME_PROMPT_DIRTY_COLOR=${POWERLINE_SCM_THEME_PROMPT_DIRTY_COLOR:=88}
SCM_THEME_PROMPT_STAGED_COLOR=${POWERLINE_SCM_THEME_PROMPT_STAGED_COLOR:=30}
SCM_THEME_PROMPT_UNSTAGED_COLOR=${POWERLINE_SCM_THEME_PROMPT_UNSTAGED_COLOR:=92}
SCM_THEME_PROMPT_COLOR=${POWERLINE_SCM_THEME_PROMPT_COLOR:=${SCM_THEME_PROMPT_CLEAN_COLOR}}

RVM_THEME_PROMPT_PREFIX="${POWERLINE_RVM_THEME_PROMPT_PREFIX:=}"
RVM_THEME_PROMPT_SUFFIX="${POWERLINE_RVM_THEME_PROMPT_SUFFIX:=}"
RBENV_THEME_PROMPT_PREFIX="${POWERLINE_RBENV_THEME_PROMPT_PREFIX:=}"
RBENV_THEME_PROMPT_SUFFIX="${POWERLINE_RBENV_THEME_PROMPT_SUFFIX:=}"
RUBY_THEME_PROMPT_COLOR=${POWERLINE_RUBY_THEME_PROMPT_COLOR:=161}
RUBY_CHAR=${POWERLINE_RUBY_CHAR:="❲r❳ "}

CWD_THEME_PROMPT_COLOR=${POWERLINE_CWD_THEME_PROMPT_COLOR:=254}

LAST_STATUS_THEME_PROMPT_COLOR=${POWERLINE_LAST_STATUS_THEME_PROMPT_COLOR:=124}

CLOCK_THEME_PROMPT_COLOR=${POWERLINE_CLOCK_THEME_PROMPT_COLOR:=240}

BATTERY_AC_CHAR=${BATTERY_AC_CHAR:="⚡"}
BATTERY_STATUS_THEME_PROMPT_GOOD_COLOR=${POWERLINE_BATTERY_STATUS_THEME_PROMPT_GOOD_COLOR:=70}
BATTERY_STATUS_THEME_PROMPT_LOW_COLOR=${POWERLINE_BATTERY_STATUS_THEME_PROMPT_LOW_COLOR:=208}
BATTERY_STATUS_THEME_PROMPT_CRITICAL_COLOR=${POWERLINE_BATTERY_STATUS_THEME_PROMPT_CRITICAL_COLOR:=160}

THEME_CLOCK_FORMAT=${THEME_CLOCK_FORMAT:="%H:%M:%S"}

IN_VIM_THEME_PROMPT_COLOR=${POWERLINE_IN_VIM_THEME_PROMPT_COLOR:=245}
IN_VIM_THEME_PROMPT_TEXT="${POWERLINE_IN_VIM_THEME_PROMPT_TEXT:=vim}"

POWERLINE_PROMPT=${POWERLINE_PROMPT:="user_info scm python_venv ruby cwd"}

function _omb_theme_PROMPT_COMMAND { __powerline_prompt_command "$@"; }
_omb_util_add_prompt_command _omb_theme_PROMPT_COMMAND
