#! bash oh-my-bash.module

#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------
#
# This theme [1] is based on the code generated by vscode-dev-container [2].
# Specifically, the code is based on the template found in Ref. [3].  The
# original code of [2] is licensed by Microsoft Corporation under the MIT
# license.
#
# [1] https://github.com/ohmybash/oh-my-bash/pull/331
# [2] https://github.com/microsoft/vscode-dev-containers
# [3] https://github.com/microsoft/vscode-dev-containers/blob/172a918f40e31bd24da8e64135026ec9f26c91b0/containers/javascript-node/.devcontainer/library-scripts/common-debian.sh#L303-L320
#
function _omb_theme_vscode_prompt {
    local exit_code=$?
    local user
    local branch=""
    local git_status=""

    # User
    if [ -n "${GITHUB_USER}" ]; then
        user="@${GITHUB_USER}"
    else
        user="\u"
    fi

    # Git branch
    if [ "$(_omb_prompt_git config --get codespaces-theme.hide-status 2>/dev/null)" != "1" ]; then
        branch=$(
            _omb_prompt_git symbolic-ref --short HEAD 2>/dev/null ||
            _omb_prompt_git rev-parse --short HEAD 2>/dev/null
        )

        if [ -n "${branch}" ]; then
            git_status="\[\033[0;36m\](\[\033[1;31m\]${branch}"

            if _omb_prompt_git ls-files \
                --error-unmatch \
                -m \
                --directory \
                --no-empty-directory \
                -o \
                --exclude-standard \
                ":/*" > /dev/null 2>&1; then
                git_status+=" \[\033[1;33m\]✗"
            fi

            git_status+="\[\033[0;36m\]) "
        fi
    fi

    # Prompt arrow
    if [ "${exit_code}" -ne 0 ]; then
        local arrow="\[\033[1;31m\]➜"
    else
        local arrow="\[\033[0m\]➜"
    fi

    PS1="\[\033[0;32m\]${user} ${arrow} \[\033[1;34m\]\w ${git_status}\[\033[0m\]\$ "
}

PROMPT_COMMAND="_omb_theme_vscode_prompt${PROMPT_COMMAND:+;$PROMPT_COMMAND}"

PROMPT_DIRTRIM=${PROMPT_DIRTRIM:-4}
