#! bash oh-my-bash.module

alias mol='molecule '
alias mhlp='molecule --help '
alias mchk='molecule check '
alias mcln='molecule cleanup '
alias mcnv='molecule converge '
alias mcrt='molecule create '
alias mdep='molecule dependency '
alias mdes='molecule destroy '
alias mdrv='molecule drivers '
alias midm='molecule idempotence '
alias minit='molecule init scenario '
alias mlst='molecule list '
alias mlgn='molecule login '
alias mtrx='molecule matrix '
alias mprp='molecule prepare '
alias mrst='molecule reset '
alias msef='molecule side-effect '
alias msyn='molecule syntax '
alias mtest='molecule test '
alias mvrf='molecule verify '
